"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import datetime
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY", "django-insecure-==i9fi#)0%@wo=1hbud_yvph5&*x4^kd0w*uo8=0#_ne=)z!@o"
)


def _is_true(x):
    return str(x).lower() in ["1", "true"]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _is_true(os.environ.get("DEBUG", "false"))

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_ez_tasks",
    "plannotations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db" / "db.sqlite3",
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


AUTH_USER_MODEL = "plannotations.User"

# Task backend configuration
TASKS = {"default": {"BACKEND": "django_ez_tasks.backends.ThreadedBackend"}}


STATIC_URL = "/static/"

# Directory for collected static files during deployment
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Additional directories where Django will look for static files in development
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "node_modules/@embedpdf/snippet/dist",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


# Logging

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)
LOG_FILE = LOG_DIR / f"plannotations_{datetime.now():%Y%m%d_%H%M%S}_{os.getpid()}.log"
LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "default": {
            "format": "%(asctime)s %(levelname)s %(name)s [pid:%(process)d]: %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "default"},
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_FILE,
            "formatter": "default",
        },
    },
    "root": {"handlers": ["console", "file"], "level": LOG_LEVEL},
}


# custom settings for plannotations
PAPERLESS_URL = os.environ.get("PAPERLESS_URL")
assert PAPERLESS_URL, "PAPERLESS_URL must be set in environment variables."
BASE_URL = os.environ.get("BASE_URL", "http://localhost:8000").rstrip("/")
CUSTOM_FIELD_NAME = os.environ.get("CUSTOM_FIELD_NAME", "Annotations")
ENABLE_AUTO_UPDATE_LINKS = _is_true(os.environ.get("ENABLE_AUTO_UPDATE_LINKS", "true"))
UPDATE_INTERVAL_MINS = int(os.environ.get("UPDATE_INTERVAL_MINS", "60"))
ANNO_SERIALIZER = os.environ.get("ANNO_SERIALIZER", "85gj")
ANNO_STORAGE = os.environ.get("ANNO_STORAGE", "paperless_notes").lower()
VERSION = "0.0.1"
